### ISSUE TITLE
Different filenames and a missing newline

### ISSUE THREAD

**Issue by Ryuzac** [TriteHexagon/Trite_ASM_Repository#2]
Route 12 is missing a newline at the end of the file, and Routes 34, 38, and 42 have different names from the current files in pokecrystal.

I don't know for sure, but I'm guessing they're meant to be Route 36 and 37, and Lake of Rage, since those are the only routes not included (besides 2 which I saw was left out on purpose). Not sure which is which besides 42 maybe being Lake of Rage though.

**Comment by Ryuzac** [comment]
Also just noticed that twelve is missing a `:` at a few spots in the night version of the song.

**Comment by TriteHexagon** [comment]
The names I use are the correct ones for those songs, and pokecrystal has had these annoyingly wrong names for a while now. I remember changing them in the past and wrote the tutorial based on those names. Since this is a repository for my own stuff, I'm not gonna change the names I use, but I'll leave a note in the readme to prevent further confusion.
